services:
  api:
    image: integracar/redeneuralbert:8.0
    container_name: integracar-api
    networks:
      - internal
    restart: unless-stopped

  frontend:
    build:
      context: .
      args:
        VITE_API_URL: /api/classificar
    container_name: frontend-classificador
    depends_on:
      - api
    networks:
      - internal
      - proxy
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  proxy:
    external: true
